// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/interaction.proto

#include "messages/interaction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace bestia {
namespace messages {
namespace interaction {
class InteractionRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<InteractionRequest> _instance;
} _InteractionRequest_default_instance_;
class InteractionResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<InteractionResponse> _instance;
} _InteractionResponse_default_instance_;
}  // namespace interaction
}  // namespace messages
}  // namespace bestia
static void InitDefaultsscc_info_InteractionRequest_messages_2finteraction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bestia::messages::interaction::_InteractionRequest_default_instance_;
    new (ptr) ::bestia::messages::interaction::InteractionRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bestia::messages::interaction::InteractionRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_InteractionRequest_messages_2finteraction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_InteractionRequest_messages_2finteraction_2eproto}, {}};

static void InitDefaultsscc_info_InteractionResponse_messages_2finteraction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bestia::messages::interaction::_InteractionResponse_default_instance_;
    new (ptr) ::bestia::messages::interaction::InteractionResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bestia::messages::interaction::InteractionResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_InteractionResponse_messages_2finteraction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_InteractionResponse_messages_2finteraction_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_messages_2finteraction_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_messages_2finteraction_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_messages_2finteraction_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_messages_2finteraction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bestia::messages::interaction::InteractionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bestia::messages::interaction::InteractionRequest, entity_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bestia::messages::interaction::InteractionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bestia::messages::interaction::InteractionResponse, entity_id_),
  PROTOBUF_FIELD_OFFSET(::bestia::messages::interaction::InteractionResponse, interactions_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bestia::messages::interaction::InteractionRequest)},
  { 6, -1, sizeof(::bestia::messages::interaction::InteractionResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bestia::messages::interaction::_InteractionRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bestia::messages::interaction::_InteractionResponse_default_instance_),
};

const char descriptor_table_protodef_messages_2finteraction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032messages/interaction.proto\022\033bestia.mes"
  "sages.interaction\"\'\n\022InteractionRequest\022"
  "\021\n\tentity_id\030\001 \001(\003\">\n\023InteractionRespons"
  "e\022\021\n\tentity_id\030\001 \001(\003\022\024\n\014interactions\030\002 \003"
  "(\tB.\n\031net.bestia.messages.protoB\021Interac"
  "tionProtosb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_messages_2finteraction_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_messages_2finteraction_2eproto_sccs[2] = {
  &scc_info_InteractionRequest_messages_2finteraction_2eproto.base,
  &scc_info_InteractionResponse_messages_2finteraction_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_messages_2finteraction_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2finteraction_2eproto = {
  false, false, descriptor_table_protodef_messages_2finteraction_2eproto, "messages/interaction.proto", 218,
  &descriptor_table_messages_2finteraction_2eproto_once, descriptor_table_messages_2finteraction_2eproto_sccs, descriptor_table_messages_2finteraction_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_messages_2finteraction_2eproto::offsets,
  file_level_metadata_messages_2finteraction_2eproto, 2, file_level_enum_descriptors_messages_2finteraction_2eproto, file_level_service_descriptors_messages_2finteraction_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_messages_2finteraction_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_messages_2finteraction_2eproto)), true);
namespace bestia {
namespace messages {
namespace interaction {

// ===================================================================

void InteractionRequest::InitAsDefaultInstance() {
}
class InteractionRequest::_Internal {
 public:
};

InteractionRequest::InteractionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bestia.messages.interaction.InteractionRequest)
}
InteractionRequest::InteractionRequest(const InteractionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  entity_id_ = from.entity_id_;
  // @@protoc_insertion_point(copy_constructor:bestia.messages.interaction.InteractionRequest)
}

void InteractionRequest::SharedCtor() {
  entity_id_ = PROTOBUF_LONGLONG(0);
}

InteractionRequest::~InteractionRequest() {
  // @@protoc_insertion_point(destructor:bestia.messages.interaction.InteractionRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void InteractionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void InteractionRequest::ArenaDtor(void* object) {
  InteractionRequest* _this = reinterpret_cast< InteractionRequest* >(object);
  (void)_this;
}
void InteractionRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void InteractionRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const InteractionRequest& InteractionRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_InteractionRequest_messages_2finteraction_2eproto.base);
  return *internal_default_instance();
}


void InteractionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:bestia.messages.interaction.InteractionRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  entity_id_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InteractionRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int64 entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* InteractionRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bestia.messages.interaction.InteractionRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 entity_id = 1;
  if (this->entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_entity_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bestia.messages.interaction.InteractionRequest)
  return target;
}

size_t InteractionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bestia.messages.interaction.InteractionRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 entity_id = 1;
  if (this->entity_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_entity_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InteractionRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bestia.messages.interaction.InteractionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const InteractionRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<InteractionRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bestia.messages.interaction.InteractionRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bestia.messages.interaction.InteractionRequest)
    MergeFrom(*source);
  }
}

void InteractionRequest::MergeFrom(const InteractionRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bestia.messages.interaction.InteractionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.entity_id() != 0) {
    _internal_set_entity_id(from._internal_entity_id());
  }
}

void InteractionRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bestia.messages.interaction.InteractionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InteractionRequest::CopyFrom(const InteractionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bestia.messages.interaction.InteractionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InteractionRequest::IsInitialized() const {
  return true;
}

void InteractionRequest::InternalSwap(InteractionRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(entity_id_, other->entity_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InteractionRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void InteractionResponse::InitAsDefaultInstance() {
}
class InteractionResponse::_Internal {
 public:
};

InteractionResponse::InteractionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  interactions_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bestia.messages.interaction.InteractionResponse)
}
InteractionResponse::InteractionResponse(const InteractionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      interactions_(from.interactions_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  entity_id_ = from.entity_id_;
  // @@protoc_insertion_point(copy_constructor:bestia.messages.interaction.InteractionResponse)
}

void InteractionResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_InteractionResponse_messages_2finteraction_2eproto.base);
  entity_id_ = PROTOBUF_LONGLONG(0);
}

InteractionResponse::~InteractionResponse() {
  // @@protoc_insertion_point(destructor:bestia.messages.interaction.InteractionResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void InteractionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void InteractionResponse::ArenaDtor(void* object) {
  InteractionResponse* _this = reinterpret_cast< InteractionResponse* >(object);
  (void)_this;
}
void InteractionResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void InteractionResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const InteractionResponse& InteractionResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_InteractionResponse_messages_2finteraction_2eproto.base);
  return *internal_default_instance();
}


void InteractionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bestia.messages.interaction.InteractionResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  interactions_.Clear();
  entity_id_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InteractionResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int64 entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string interactions = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_interactions();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bestia.messages.interaction.InteractionResponse.interactions"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* InteractionResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bestia.messages.interaction.InteractionResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 entity_id = 1;
  if (this->entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_entity_id(), target);
  }

  // repeated string interactions = 2;
  for (int i = 0, n = this->_internal_interactions_size(); i < n; i++) {
    const auto& s = this->_internal_interactions(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bestia.messages.interaction.InteractionResponse.interactions");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bestia.messages.interaction.InteractionResponse)
  return target;
}

size_t InteractionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bestia.messages.interaction.InteractionResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string interactions = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(interactions_.size());
  for (int i = 0, n = interactions_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      interactions_.Get(i));
  }

  // int64 entity_id = 1;
  if (this->entity_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_entity_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InteractionResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bestia.messages.interaction.InteractionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const InteractionResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<InteractionResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bestia.messages.interaction.InteractionResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bestia.messages.interaction.InteractionResponse)
    MergeFrom(*source);
  }
}

void InteractionResponse::MergeFrom(const InteractionResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bestia.messages.interaction.InteractionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  interactions_.MergeFrom(from.interactions_);
  if (from.entity_id() != 0) {
    _internal_set_entity_id(from._internal_entity_id());
  }
}

void InteractionResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bestia.messages.interaction.InteractionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InteractionResponse::CopyFrom(const InteractionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bestia.messages.interaction.InteractionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InteractionResponse::IsInitialized() const {
  return true;
}

void InteractionResponse::InternalSwap(InteractionResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  interactions_.InternalSwap(&other->interactions_);
  swap(entity_id_, other->entity_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InteractionResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace interaction
}  // namespace messages
}  // namespace bestia
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bestia::messages::interaction::InteractionRequest* Arena::CreateMaybeMessage< ::bestia::messages::interaction::InteractionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bestia::messages::interaction::InteractionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::bestia::messages::interaction::InteractionResponse* Arena::CreateMaybeMessage< ::bestia::messages::interaction::InteractionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bestia::messages::interaction::InteractionResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
